### ISSUE TITLE
LoRa bandwidth, spreading factor, and coding rate

### ISSUE THREAD

**Issue by syedkarim** [Othernet-Project/Dreamcatcher-Packet-Tester#3]
Bandwidth
203 kHz
406 kHz
812 kHz
1625 kHz

Spreading Factor
5, 6, 7, 8, 9, 10, 11, 12

Coding Rate
4/8, 5/8, 6/8, 7/8

**Comment by abgoyal** [comment]
can be changed by user via recompile - as compiling now works. params can be edited inside main.cpp around line no 370.
